"""
Utilitaire pour la validation et la gestion des codes pays ISO 3166-1 alpha-2.
"""

# Liste complète des codes pays ISO 3166-1 alpha-2
VALID_COUNTRY_CODES = {
    "AD": "Andorre",
    "AE": "Émirats Arabes Unis",
    "AF": "Afghanistan",
    "AG": "Antigua-et-Barbuda",
    "AI": "Anguilla",
    "AL": "Albanie",
    "AM": "Arménie",
    "AO": "Angola",
    "AQ": "Antarctique",
    "AR": "Argentine",
    "AS": "Samoa Américaines",
    "AT": "Autriche",
    "AU": "Australie",
    "AW": "Aruba",
    "AX": "Îles Åland",
    "AZ": "Azerbaïdjan",
    "BA": "Bosnie-Herzégovine",
    "BB": "Barbade",
    "BD": "Bangladesh",
    "BE": "Belgique",
    "BF": "Burkina Faso",
    "BG": "Bulgarie",
    "BH": "Bahreïn",
    "BI": "Burundi",
    "BJ": "Bénin",
    "BL": "Saint-Barthélemy",
    "BM": "Bermudes",
    "BN": "Brunei",
    "BO": "Bolivie",
    "BQ": "Bonaire, Saint-Eustache et Saba",
    "BR": "Brésil",
    "BS": "Bahamas",
    "BT": "Bhoutan",
    "BV": "Île Bouvet",
    "BW": "Botswana",
    "BY": "Biélorussie",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Îles Cocos",
    "CD": "Congo (RDC)",
    "CF": "République Centrafricaine",
    "CG": "Congo",
    "CH": "Suisse",
    "CI": "Côte d'Ivoire",
    "CK": "Îles Cook",
    "CL": "Chili",
    "CM": "Cameroun",
    "CN": "Chine",
    "CO": "Colombie",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cap-Vert",
    "CW": "Curaçao",
    "CX": "Île Christmas",
    "CY": "Chypre",
    "CZ": "Tchéquie",
    "DE": "Allemagne",
    "DJ": "Djibouti",
    "DK": "Danemark",
    "DM": "Dominique",
    "DO": "République Dominicaine",
    "DZ": "Algérie",
    "EC": "Équateur",
    "EE": "Estonie",
    "EG": "Égypte",
    "EH": "Sahara Occidental",
    "ER": "Érythrée",
    "ES": "Espagne",
    "ET": "Éthiopie",
    "FI": "Finlande",
    "FJ": "Fidji",
    "FK": "Îles Malouines",
    "FM": "Micronésie",
    "FO": "Îles Féroé",
    "FR": "France",
    "GA": "Gabon",
    "GB": "Royaume-Uni",
    "GD": "Grenade",
    "GE": "Géorgie",
    "GF": "Guyane Française",
    "GG": "Guernesey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Groenland",
    "GM": "Gambie",
    "GN": "Guinée",
    "GP": "Guadeloupe",
    "GQ": "Guinée Équatoriale",
    "GR": "Grèce",
    "GS": "Géorgie du Sud et Îles Sandwich du Sud",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinée-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HM": "Îles Heard et McDonald",
    "HN": "Honduras",
    "HR": "Croatie",
    "HT": "Haïti",
    "HU": "Hongrie",
    "ID": "Indonésie",
    "IE": "Irlande",
    "IL": "Israël",
    "IM": "Île de Man",
    "IN": "Inde",
    "IO": "Territoire Britannique de l'Océan Indien",
    "IQ": "Irak",
    "IR": "Iran",
    "IS": "Islande",
    "IT": "Italie",
    "JE": "Jersey",
    "JM": "Jamaïque",
    "JO": "Jordanie",
    "JP": "Japon",
    "KE": "Kenya",
    "KG": "Kirghizistan",
    "KH": "Cambodge",
    "KI": "Kiribati",
    "KM": "Comores",
    "KN": "Saint-Christophe-et-Niévès",
    "KP": "Corée du Nord",
    "KR": "Corée du Sud",
    "KW": "Koweït",
    "KY": "Îles Caïmans",
    "KZ": "Kazakhstan",
    "LA": "Laos",
    "LB": "Liban",
    "LC": "Sainte-Lucie",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lituanie",
    "LU": "Luxembourg",
    "LV": "Lettonie",
    "LY": "Libye",
    "MA": "Maroc",
    "MC": "Monaco",
    "MD": "Moldavie",
    "ME": "Monténégro",
    "MF": "Saint-Martin (partie française)",
    "MG": "Madagascar",
    "MH": "Îles Marshall",
    "MK": "Macédoine du Nord",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolie",
    "MO": "Macao",
    "MP": "Îles Mariannes du Nord",
    "MQ": "Martinique",
    "MR": "Mauritanie",
    "MS": "Montserrat",
    "MT": "Malte",
    "MU": "Maurice",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexique",
    "MY": "Malaisie",
    "MZ": "Mozambique",
    "NA": "Namibie",
    "NC": "Nouvelle-Calédonie",
    "NE": "Niger",
    "NF": "Île Norfolk",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Pays-Bas",
    "NO": "Norvège",
    "NP": "Népal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "Nouvelle-Zélande",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Pérou",
    "PF": "Polynésie Française",
    "PG": "Papouasie-Nouvelle-Guinée",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Pologne",
    "PM": "Saint-Pierre-et-Miquelon",
    "PN": "Îles Pitcairn",
    "PR": "Porto Rico",
    "PS": "Palestine",
    "PT": "Portugal",
    "PW": "Palaos",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RE": "La Réunion",
    "RO": "Roumanie",
    "RS": "Serbie",
    "RU": "Russie",
    "RW": "Rwanda",
    "SA": "Arabie Saoudite",
    "SB": "Îles Salomon",
    "SC": "Seychelles",
    "SD": "Soudan",
    "SE": "Suède",
    "SG": "Singapour",
    "SH": "Sainte-Hélène",
    "SI": "Slovénie",
    "SJ": "Svalbard et Jan Mayen",
    "SK": "Slovaquie",
    "SL": "Sierra Leone",
    "SM": "Saint-Marin",
    "SN": "Sénégal",
    "SO": "Somalie",
    "SR": "Suriname",
    "SS": "Soudan du Sud",
    "ST": "Sao Tomé-et-Principe",
    "SV": "Salvador",
    "SX": "Saint-Martin (partie néerlandaise)",
    "SY": "Syrie",
    "SZ": "Eswatini",
    "TC": "Îles Turques-et-Caïques",
    "TD": "Tchad",
    "TF": "Terres Australes Françaises",
    "TG": "Togo",
    "TH": "Thaïlande",
    "TJ": "Tadjikistan",
    "TK": "Tokelau",
    "TL": "Timor Oriental",
    "TM": "Turkménistan",
    "TN": "Tunisie",
    "TO": "Tonga",
    "TR": "Turquie",
    "TT": "Trinité-et-Tobago",
    "TV": "Tuvalu",
    "TW": "Taïwan",
    "TZ": "Tanzanie",
    "UA": "Ukraine",
    "UG": "Ouganda",
    "UM": "Îles Mineures Éloignées des États-Unis",
    "US": "États-Unis",
    "UY": "Uruguay",
    "UZ": "Ouzbékistan",
    "VA": "Vatican",
    "VC": "Saint-Vincent-et-les-Grenadines",
    "VE": "Venezuela",
    "VG": "Îles Vierges Britanniques",
    "VI": "Îles Vierges des États-Unis",
    "VN": "Vietnam",
    "VU": "Vanuatu",
    "WF": "Wallis-et-Futuna",
    "WS": "Samoa",
    "YE": "Yémen",
    "YT": "Mayotte",
    "ZA": "Afrique du Sud",
    "ZM": "Zambie",
    "ZW": "Zimbabwe",
}


def is_valid_country_code(code: str | None) -> bool:
    """
    Vérifie si un code pays est valide selon la norme ISO 3166-1 alpha-2.
    
    Args:
        code: Code pays à valider (2 lettres)
        
    Returns:
        True si le code est valide, False sinon
    """
    if code is None:
        return True  # NULL est accepté
    return code.upper() in VALID_COUNTRY_CODES


def normalize_country_code(code: str | None) -> str | None:
    """
    Normalise un code pays en majuscules.
    
    Args:
        code: Code pays à normaliser
        
    Returns:
        Code pays en majuscules ou None
    """
    if code is None:
        return None
    return code.upper().strip()


def get_country_name(code: str) -> str | None:
    """
    Retourne le nom du pays à partir de son code ISO.
    
    Args:
        code: Code pays ISO 3166-1 alpha-2
        
    Returns:
        Nom du pays en français ou None si code invalide
    """
    return VALID_COUNTRY_CODES.get(code.upper())


def get_all_countries() -> list[dict[str, str]]:
    """
    Retourne la liste complète des pays disponibles.
    
    Returns:
        Liste de dictionnaires avec code et nom
    """
    return [{"code": code, "name": name} for code, name in sorted(VALID_COUNTRY_CODES.items(), key=lambda x: x[1])]
